/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/venues/{venueId}/sections/{sectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename a Section or change its capacity
         * @description A Section's kind can't change.
         */
        put: operations["change"];
        post?: never;
        /** Remove a Section and its Seats */
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A Venue with its Sections and Seats
         * @description Public for approved Venues. Signed in, you also see your own Venues in any status.
         */
        get: operations["venue"];
        /** Change a draft or rejected Venue's details */
        put: operations["change_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A Show with its Venue and each Section's price, capacity or Seats
         * @description Public for published Shows. Signed in, you also see your own drafts, whose Sections may not have a price yet.
         */
        get: operations["show"];
        /**
         * Move one of your draft Shows to another start time or Venue
         * @description Moving it to another Venue drops the prices of Sections the new Venue doesn't have. Send the version you last read; if the Show has changed since, you get 409.
         */
        put: operations["reschedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace every Section Price of one of your draft Shows
         * @description Only Sections of the Show's Venue, each at most once. Every Section needs a price before the Show can be published.
         */
        put: operations["reprice"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An Event
         * @description Public for published Events. Signed in, you also see your own drafts.
         */
        get: operations["event"];
        /**
         * Edit one of your Events, draft or published
         * @description Send the version you last read; if the Event has changed since, you get 409 and should reload it.
         */
        put: operations["change_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search approved Venues
         * @description Public. q matches part of the name and city matches the whole city, both ignoring case.
         */
        get: operations["search"];
        put?: never;
        /**
         * Propose a Venue
         * @description It starts as a draft. Add Sections, then submit it for review.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{venueId}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a Section
         * @description Seated Sections take rows of Seats: a row label and either a seatCount (Seats 1 to n) or a list of seatNumbers. General Admission Sections take a capacity instead.
         */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{venueId}/sections/{sectionId}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add rows of Seats to a Seated Section */
        post: operations["addSeats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a Venue for Admin review
         * @description Needs at least one Section, and Seats in every Seated Section. A rejected Venue can be resubmitted.
         */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish one of your draft Shows
         * @description Needs a published Event, an approved Venue, a future start time and a price for every Section. Once published, its Venue, start time and prices are locked.
         */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}/holds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hold Seats and General Admission places at a published Show
         * @description All or nothing, 1 to 10 tickets. Prices are the Section Prices at the moment of the Hold, and the Hold expires after the Hold time, 10 minutes by default. You have at most one active Hold per Show: a new one releases your previous Hold for the Show, so it can include the same Seats. If anything you asked for is gone, nothing is held, your previous Hold stays active, and you get 409 naming what's unavailable. A draft or unknown Show is 404; a Show that has started is 409. Send an Idempotency-Key with every Hold: a retry with the same key and request (the Show and the same items, in any order) returns 201 with the original Hold as it is now, and holds nothing more. A request that fails leaves the key unused, so its retry tries again.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizer-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply to become an Organizer
         * @description Your name and email are taken from your token. You can have one pending application at a time.
         */
        post: operations["submit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holds/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release one of your Holds early
         * @description Its Seats and General Admission places become available again. Anyone else's Hold is 404; a Hold that has expired, or otherwise isn't active, is 409.
         */
        post: operations["release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search published Events, most recently published first
         * @description Public. q matches part of the title or description, ignoring case. city, from and to match Events with at least one upcoming published Show in that city (ignoring case) starting between those dates, inclusive, in the Venue's time zone.
         */
        get: operations["search_1"];
        put?: never;
        /**
         * Create an Event
         * @description It starts as a draft that only you can see.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish one of your draft Events
         * @description Anyone can see it once it's published.
         */
        post: operations["publish_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}/shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An Event's upcoming Shows, soonest first, with their Venue
         * @description Public: published Shows that haven't started. Signed in as the Event's owner, you see all its Shows, drafts and past ones included.
         */
        get: operations["ofEvent"];
        put?: never;
        /**
         * Schedule a Show of one of your Events
         * @description At an approved Venue and a future start time. It starts as a draft that only you can see.
         */
        post: operations["schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/venues/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a Venue with a reason
         * @description The Organizer can fix it and resubmit.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/venues/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a Venue
         * @description Its layout is then fixed and any Organizer can use it.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizer-applications/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject an application with a reason */
        post: operations["reject_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizer-applications/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve an application and grant the ORGANIZER role
         * @description The applicant gets the role on their next token refresh. Returns 503 and leaves the application pending if Keycloak can't be reached.
         */
        post: operations["approve_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The Venues you proposed, in any status */
        get: operations["mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}/holds/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your active Hold for a Show
         * @description 404 if you have none. An active Hold past its expiry time expires right then and gives back its inventory, so it's 404 too.
         */
        get: operations["mine_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shows/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What's left to sell at a published Show
         * @description Public. For each Section, in layout order: every Seat of a Seated Section with whether it's available, or a General Admission Section's capacity and how many places are left. A draft or unknown Show is 404.
         */
        get: operations["availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizer-applications/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your latest Organizer Application */
        get: operations["mine_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who the API thinks the caller is
         * @description Roles come from the access token, so a newly granted role appears after the token is refreshed.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One of your Holds
         * @description An active Hold read after its expiry time expires right then, gives back its inventory and comes back EXPIRED. Anyone else's Hold is 404.
         */
        get: operations["find"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your Events, drafts included, newest first */
        get: operations["mine_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Venues to review, with their full layout
         * @description Oldest submission first. Filter by status, such as PENDING_REVIEW.
         */
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/organizer-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The Organizer Application queue, oldest first
         * @description Filter by status to see pending applications or look back at past decisions.
         */
        get: operations["queue_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/venues/{venueId}/sections/{sectionId}/seats/{seatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a Seat */
        delete: operations["removeSeat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SectionRequest: {
            name: string;
            /** Format: int32 */
            capacity?: number;
        };
        SeatResponse: {
            /** Format: uuid */
            id?: string;
            row?: string;
            /** Format: int32 */
            number?: number;
            label?: string;
        };
        SectionResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            kind?: "SEATED" | "GENERAL_ADMISSION";
            /** Format: int32 */
            capacity?: number;
            seats?: components["schemas"]["SeatResponse"][];
        };
        VenueRequest: {
            name: string;
            address: string;
            city: string;
            timeZone: string;
        };
        VenueResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            address?: string;
            city?: string;
            timeZone?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "REJECTED";
            rejectionReason?: string;
            /** Format: uuid */
            ownerSubject?: string;
            /** Format: date-time */
            submittedAt?: string;
            /** Format: uuid */
            decidedBy?: string;
            /** Format: date-time */
            decidedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            sections?: components["schemas"]["SectionResponse"][];
        };
        ShowRequest: {
            /** Format: uuid */
            venueId: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: int64 */
            version?: number;
        };
        PriceResponse: {
            /** Format: uuid */
            sectionId?: string;
            /** Format: int64 */
            amountPaise?: number;
            currency?: string;
        };
        ShowResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            eventId?: string;
            /** Format: uuid */
            venueId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
            prices?: components["schemas"]["PriceResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        PriceRequest: {
            /** Format: uuid */
            sectionId: string;
            /** Format: int64 */
            amountPaise: number;
            currency: string;
        };
        PricesRequest: {
            prices: components["schemas"]["PriceRequest"][];
        };
        EventRequest: {
            title: string;
            description: string;
            /** @enum {string} */
            category: "MUSIC" | "COMEDY" | "THEATRE" | "DANCE" | "SPORTS" | "CONFERENCE" | "WORKSHOP" | "FAMILY" | "OTHER";
            language: string;
            /** Format: int64 */
            version?: number;
        };
        EventResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            category?: "MUSIC" | "COMEDY" | "THEATRE" | "DANCE" | "SPORTS" | "CONFERENCE" | "WORKSHOP" | "FAMILY" | "OTHER";
            language?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
            /** Format: uuid */
            ownerSubject?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        NewSectionRequest: {
            name: string;
            /** @enum {string} */
            kind: "SEATED" | "GENERAL_ADMISSION";
            /** Format: int32 */
            capacity?: number;
            rows?: components["schemas"]["SeatRow"][];
        };
        SeatRow: {
            label?: string;
            /** Format: int32 */
            seatCount?: number;
            seatNumbers?: number[];
        };
        SeatsRequest: {
            rows: components["schemas"]["SeatRow"][];
        };
        HoldRequest: {
            seats?: string[];
            generalAdmission?: components["schemas"]["PlacesRequest"][];
        };
        PlacesRequest: {
            /** Format: uuid */
            sectionId: string;
            /** Format: int32 */
            quantity: number;
        };
        InventoryUnavailableProblem: {
            /**
             * Format: uri
             * @example urn:getmyseat:problem:inventory-unavailable
             */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** @description Seats that someone else holds; empty if a race with other Holds was the cause */
            unavailableSeats?: string[];
            /** @description General Admission Sections without enough places left, and how many are left */
            unavailableSections?: components["schemas"]["UnavailableSection"][];
        };
        UnavailableSection: {
            /** Format: uuid */
            sectionId?: string;
            /** Format: int32 */
            available?: number;
        };
        HoldItemResponse: {
            /** @enum {string} */
            kind?: "SEAT" | "GENERAL_ADMISSION";
            /** Format: uuid */
            sectionId?: string;
            /** Format: uuid */
            seatId?: string;
            rowLabel?: string;
            /** Format: int32 */
            seatNumber?: number;
            /** Format: int32 */
            quantity?: number;
            /** Format: int64 */
            pricePaise?: number;
        };
        HoldResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            showId?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "RELEASED" | "EXPIRED";
            /** Format: date-time */
            expiresAt?: string;
            items?: components["schemas"]["HoldItemResponse"][];
            /** Format: int64 */
            totalPaise?: number;
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SubmitRequest: {
            organisationName: string;
            contactPhone: string;
            description: string;
        };
        OrganizerApplicationResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "REJECTED";
            /** Format: uuid */
            applicantSubject?: string;
            applicantName?: string;
            applicantEmail?: string;
            organisationName?: string;
            contactPhone?: string;
            description?: string;
            rejectionReason?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            decidedBy?: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        RejectRequest: {
            reason: string;
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelVenueSummary: {
            content?: components["schemas"]["VenueSummary"][];
            page?: components["schemas"]["PageMetadata"];
        };
        VenueSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            address?: string;
            city?: string;
            timeZone?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "REJECTED";
        };
        Price: {
            /** Format: int64 */
            amountPaise?: number;
            currency?: string;
        };
        SectionDetail: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            kind?: "SEATED" | "GENERAL_ADMISSION";
            price?: components["schemas"]["Price"];
            /** Format: int32 */
            capacity?: number;
            seats?: components["schemas"]["SeatResponse"][];
        };
        ShowDetail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            eventId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
            venue?: components["schemas"]["ShowVenue"];
            sections?: components["schemas"]["SectionDetail"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            publishedAt?: string;
            /** Format: int64 */
            version?: number;
        };
        ShowVenue: {
            /** Format: uuid */
            id?: string;
            name?: string;
            address?: string;
            city?: string;
            timeZone?: string;
        };
        SeatAvailability: {
            /** Format: uuid */
            id?: string;
            available?: boolean;
        };
        SectionAvailability: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            kind?: "SEATED" | "GENERAL_ADMISSION";
            seats?: components["schemas"]["SeatAvailability"][];
            /** Format: int32 */
            capacity?: number;
            /** Format: int32 */
            available?: number;
        };
        ShowAvailability: {
            /** Format: uuid */
            showId?: string;
            sections?: components["schemas"]["SectionAvailability"][];
        };
        MeResponse: {
            /** Format: uuid */
            subject?: string;
            name?: string;
            email?: string;
            roles?: ("CUSTOMER" | "ORGANIZER" | "ADMIN")[];
        };
        PagedModelEventResponse: {
            content?: components["schemas"]["EventResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelShowSummary: {
            content?: components["schemas"]["ShowSummary"][];
            page?: components["schemas"]["PageMetadata"];
        };
        ShowSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            eventId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
            venue?: components["schemas"]["ShowVenue"];
        };
        PagedModelVenueResponse: {
            content?: components["schemas"]["VenueResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelOrganizerApplicationResponse: {
            content?: components["schemas"]["OrganizerApplicationResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
                sectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
                sectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    venue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    change_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowDetail"];
                };
            };
        };
    };
    reschedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowResponse"];
                };
            };
        };
    };
    reprice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PricesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowResponse"];
                };
            };
        };
    };
    event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    change_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                city?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelVenueSummary"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    addSeats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
                sectionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SectionResponse"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header: {
                /** @description Your own key for this request, 1 to 255 characters, such as a fresh UUID. Retry with the same key and the same request to get the original Hold back; the key is yours alone and is forgotten after 24 hours. */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            /** @description Held, or the Hold that an earlier request with the same Idempotency-Key made */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldResponse"];
                };
            };
            /** @description The request is invalid, or the Idempotency-Key header is missing or not 1 to 255 characters (type urn:getmyseat:problem:validation) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description No published Show with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Some of the inventory is unavailable (type urn:getmyseat:problem:inventory-unavailable), you used the Idempotency-Key before for a different request (type urn:getmyseat:problem:idempotency-key-reused), or the Show has started or you were making another Hold for it at the same moment (type urn:getmyseat:problem:conflict) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["InventoryUnavailableProblem"];
                };
            };
        };
    };
    submit_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizerApplicationResponse"];
                };
            };
        };
    };
    release: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldResponse"];
                };
            };
            /** @description No Hold of yours with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description The Hold has expired or isn't active, or other Holds were in flight for the same inventory (try again) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    search_1: {
        parameters: {
            query?: {
                q?: string;
                city?: string;
                category?: "MUSIC" | "COMEDY" | "THEATRE" | "DANCE" | "SPORTS" | "CONFERENCE" | "WORKSHOP" | "FAMILY" | "OTHER";
                /** @description ISO date such as 2026-10-01 */
                from?: string;
                /** @description ISO date such as 2026-10-31 */
                to?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelEventResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    publish_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    ofEvent: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelShowSummary"];
                };
            };
        };
    };
    schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShowRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueResponse"];
                };
            };
        };
    };
    reject_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizerApplicationResponse"];
                };
            };
        };
    };
    approve_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizerApplicationResponse"];
                };
            };
        };
    };
    mine: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelVenueSummary"];
                };
            };
        };
    };
    mine_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your active Hold */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldResponse"];
                };
            };
            /** @description You have no active Hold for the Show */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Your Hold was expiring while other Holds were in flight for the same inventory (try again) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    availability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Show's availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ShowAvailability"];
                };
            };
            /** @description No published Show with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    mine_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OrganizerApplicationResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    find: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Your Hold */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HoldResponse"];
                };
            };
            /** @description No Hold of yours with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
            /** @description Your Hold was expiring while other Holds were in flight for the same inventory (try again) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    mine_3: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelEventResponse"];
                };
            };
        };
    };
    queue: {
        parameters: {
            query?: {
                status?: "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "REJECTED";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelVenueResponse"];
                };
            };
        };
    };
    queue_1: {
        parameters: {
            query?: {
                status?: "PENDING" | "APPROVED" | "REJECTED";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelOrganizerApplicationResponse"];
                };
            };
        };
    };
    removeSeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
                sectionId: string;
                seatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
